version: "3"
services:
  web:
    build: .
    container_name: my-html-app
    restart: always
    environment:
      - VIRTUAL_HOST=mywebsite.com
      - LETSENCRYPT_HOST=mywebsite.com
      - LETSENCRYPT_EMAIL=youremail@example.com

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=youremail@example.com
  